//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFT.Trainer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFT.Trainer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dump ähnelt.
        /// </summary>
        internal static string CommandDump {
            get {
                return ResourceManager.GetString("CommandDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dumping game objects... ähnelt.
        /// </summary>
        internal static string CommandDumpGameObjects {
            get {
                return ResourceManager.GetString("CommandDumpGameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dumping Scenes... ähnelt.
        /// </summary>
        internal static string CommandDumpScenes {
            get {
                return ResourceManager.GetString("CommandDumpScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dump created in {0} ähnelt.
        /// </summary>
        internal static string CommandDumpSuccessFormat {
            get {
                return ResourceManager.GetString("CommandDumpSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die list ähnelt.
        /// </summary>
        internal static string CommandList {
            get {
                return ResourceManager.GetString("CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} [{1}] {2} ähnelt.
        /// </summary>
        internal static string CommandListEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandListEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die listr ähnelt.
        /// </summary>
        internal static string CommandListRare {
            get {
                return ResourceManager.GetString("CommandListRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ({0}) ähnelt.
        /// </summary>
        internal static string CommandListRarityFormat {
            get {
                return ResourceManager.GetString("CommandListRarityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found {0} item(s) ähnelt.
        /// </summary>
        internal static string CommandListSuccessFormat {
            get {
                return ResourceManager.GetString("CommandListSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die listsr ähnelt.
        /// </summary>
        internal static string CommandListSuperRare {
            get {
                return ResourceManager.GetString("CommandListSuperRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load settings ähnelt.
        /// </summary>
        internal static string CommandLoadDescription {
            get {
                return ResourceManager.GetString("CommandLoadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die load ähnelt.
        /// </summary>
        internal static string CommandLoadName {
            get {
                return ResourceManager.GetString("CommandLoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loaded {0} ähnelt.
        /// </summary>
        internal static string CommandLoadSuccessFormat {
            get {
                return ResourceManager.GetString("CommandLoadSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loadtl ähnelt.
        /// </summary>
        internal static string CommandLoadTrackList {
            get {
                return ResourceManager.GetString("CommandLoadTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save settings ähnelt.
        /// </summary>
        internal static string CommandSaveDescription {
            get {
                return ResourceManager.GetString("CommandSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Be careful when updating this file :)
        ///For keys, use https://docs.unity3d.com/ScriptReference/KeyCode.html
        ///Colors are stored as an array of &apos;RGBA&apos; floats ähnelt.
        /// </summary>
        internal static string CommandSaveHeader {
            get {
                return ResourceManager.GetString("CommandSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        internal static string CommandSaveName {
            get {
                return ResourceManager.GetString("CommandSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved {0} ähnelt.
        /// </summary>
        internal static string CommandSaveSuccessFormat {
            get {
                return ResourceManager.GetString("CommandSaveSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die savetl ähnelt.
        /// </summary>
        internal static string CommandSaveTrackList {
            get {
                return ResourceManager.GetString("CommandSaveTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die spawn ähnelt.
        /// </summary>
        internal static string CommandSpawn {
            get {
                return ResourceManager.GetString("CommandSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die spawnbot ähnelt.
        /// </summary>
        internal static string CommandSpawnBot {
            get {
                return ResourceManager.GetString("CommandSpawnBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string CommandSpawnBotEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandSpawnBotEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die spawnhi ähnelt.
        /// </summary>
        internal static string CommandSpawnHideoutItems {
            get {
                return ResourceManager.GetString("CommandSpawnHideoutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die spawnqi ähnelt.
        /// </summary>
        internal static string CommandSpawnQuestItems {
            get {
                return ResourceManager.GetString("CommandSpawnQuestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die status ähnelt.
        /// </summary>
        internal static string CommandStatus {
            get {
                return ResourceManager.GetString("CommandStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is {1} {2} ähnelt.
        /// </summary>
        internal static string CommandStatusTextFormat {
            get {
                return ResourceManager.GetString("CommandStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ({0} to toggle) ähnelt.
        /// </summary>
        internal static string CommandStatusTextToggleFormat {
            get {
                return ResourceManager.GetString("CommandStatusTextToggleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die template ähnelt.
        /// </summary>
        internal static string CommandTemplate {
            get {
                return ResourceManager.GetString("CommandTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: {1} [{2}] ähnelt.
        /// </summary>
        internal static string CommandTemplateEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandTemplateEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found {0} template(s) ähnelt.
        /// </summary>
        internal static string CommandTemplateSuccessFormat {
            get {
                return ResourceManager.GetString("CommandTemplateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die track ähnelt.
        /// </summary>
        internal static string CommandTrack {
            get {
                return ResourceManager.GetString("CommandTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tracklist ähnelt.
        /// </summary>
        internal static string CommandTrackList {
            get {
                return ResourceManager.GetString("CommandTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking: {0} {1} ähnelt.
        /// </summary>
        internal static string CommandTrackListEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandTrackListEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ({0}) ähnelt.
        /// </summary>
        internal static string CommandTrackListRarityFormat {
            get {
                return ResourceManager.GetString("CommandTrackListRarityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking list updated... ähnelt.
        /// </summary>
        internal static string CommandTrackListUpdated {
            get {
                return ResourceManager.GetString("CommandTrackListUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking: {0} (Wishlist) ähnelt.
        /// </summary>
        internal static string CommandTrackListWishListEnumerateFormat {
            get {
                return ResourceManager.GetString("CommandTrackListWishListEnumerateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die trackr ähnelt.
        /// </summary>
        internal static string CommandTrackRare {
            get {
                return ResourceManager.GetString("CommandTrackRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tracksr ähnelt.
        /// </summary>
        internal static string CommandTrackSuperRare {
            get {
                return ResourceManager.GetString("CommandTrackSuperRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die untrack ähnelt.
        /// </summary>
        internal static string CommandUnTrack {
            get {
                return ResourceManager.GetString("CommandUnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patched {0} with {1} ähnelt.
        /// </summary>
        internal static string DebugPatchedMethodFormat {
            get {
                return ResourceManager.GetString("DebugPatchedMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refreshed {0} in {1}ms ähnelt.
        /// </summary>
        internal static string DebugPerformanceRefreshedFormat {
            get {
                return ResourceManager.GetString("DebugPerformanceRefreshedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registering {0} command... ähnelt.
        /// </summary>
        internal static string DebugRegisteringCommandFormat {
            get {
                return ResourceManager.GetString("DebugRegisteringCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registering {0} command with arguments... ähnelt.
        /// </summary>
        internal static string DebugRegisteringCommandWithArgumentsFormat {
            get {
                return ResourceManager.GetString("DebugRegisteringCommandWithArgumentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E ähnelt.
        /// </summary>
        internal static string DirectionEast {
            get {
                return ResourceManager.GetString("DirectionEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N ähnelt.
        /// </summary>
        internal static string DirectionNorth {
            get {
                return ResourceManager.GetString("DirectionNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NE ähnelt.
        /// </summary>
        internal static string DirectionNorthEast {
            get {
                return ResourceManager.GetString("DirectionNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NW ähnelt.
        /// </summary>
        internal static string DirectionNorthWest {
            get {
                return ResourceManager.GetString("DirectionNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S ähnelt.
        /// </summary>
        internal static string DirectionSouth {
            get {
                return ResourceManager.GetString("DirectionSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SE ähnelt.
        /// </summary>
        internal static string DirectionSouthEast {
            get {
                return ResourceManager.GetString("DirectionSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SW ähnelt.
        /// </summary>
        internal static string DirectionSouthWest {
            get {
                return ResourceManager.GetString("DirectionSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die W ähnelt.
        /// </summary>
        internal static string DirectionWest {
            get {
                return ResourceManager.GetString("DirectionWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to find {0} on {1} ähnelt.
        /// </summary>
        internal static string ErrorCannotFindField {
            get {
                return ResourceManager.GetString("ErrorCannotFindField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot find original method {0} ähnelt.
        /// </summary>
        internal static string ErrorCannotFindOriginalMethodFormat {
            get {
                return ResourceManager.GetString("ErrorCannotFindOriginalMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot find postfix method {0} ähnelt.
        /// </summary>
        internal static string ErrorCannotFindPostfixMethodFormat {
            get {
                return ResourceManager.GetString("ErrorCannotFindPostfixMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot find prefix method {0} ähnelt.
        /// </summary>
        internal static string ErrorCannotFindPrefixMethodFormat {
            get {
                return ResourceManager.GetString("ErrorCannotFindPrefixMethodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to load {0}. {1} ähnelt.
        /// </summary>
        internal static string ErrorCannotLoadFormat {
            get {
                return ResourceManager.GetString("ErrorCannotLoadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save {0}. {1} ähnelt.
        /// </summary>
        internal static string ErrorCannotSaveFormat {
            get {
                return ResourceManager.GetString("ErrorCannotSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} seems corrupted. Please fix ähnelt.
        /// </summary>
        internal static string ErrorCorruptedFileFormat {
            get {
                return ResourceManager.GetString("ErrorCorruptedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} seems corrupted in {1}. Please fix ähnelt.
        /// </summary>
        internal static string ErrorCorruptedPropertyFormat {
            get {
                return ResourceManager.GetString("ErrorCorruptedPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to create item! ähnelt.
        /// </summary>
        internal static string ErrorFailedToCreateItem {
            get {
                return ResourceManager.GetString("ErrorFailedToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load item bundle! ähnelt.
        /// </summary>
        internal static string ErrorFailedToLoadItemBundle {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadItemBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} not found! ähnelt.
        /// </summary>
        internal static string ErrorFileNotFoundFormat {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid arguments ähnelt.
        /// </summary>
        internal static string ErrorInvalidArguments {
            get {
                return ResourceManager.GetString("ErrorInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No bot found! ähnelt.
        /// </summary>
        internal static string ErrorNoBotFound {
            get {
                return ResourceManager.GetString("ErrorNoBotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No template found! ähnelt.
        /// </summary>
        internal static string ErrorNoTemplateFound {
            get {
                return ResourceManager.GetString("ErrorNoTemplateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found {0} bots, be more specific ähnelt.
        /// </summary>
        internal static string ErrorTooManyBotsFormat {
            get {
                return ResourceManager.GetString("ErrorTooManyBotsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found {0} templates, be more specific ähnelt.
        /// </summary>
        internal static string ErrorTooManyTemplatesFormat {
            get {
                return ResourceManager.GetString("ErrorTooManyTemplatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsupported type: {0} ähnelt.
        /// </summary>
        internal static string ErrorUnsupportedTypeFormat {
            get {
                return ResourceManager.GetString("ErrorUnsupportedTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aimbot. Automatic aiming and/or shooting (SilentAim). ähnelt.
        /// </summary>
        internal static string FeatureAimbotDescription {
            get {
                return ResourceManager.GetString("FeatureAimbotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die aimbot ähnelt.
        /// </summary>
        internal static string FeatureAimbotName {
            get {
                return ResourceManager.GetString("FeatureAimbotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Triggers an airdrop at the player&apos;s location. ähnelt.
        /// </summary>
        internal static string FeatureAirDropDescription {
            get {
                return ResourceManager.GetString("FeatureAirDropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die airdrop ähnelt.
        /// </summary>
        internal static string FeatureAirDropName {
            get {
                return ResourceManager.GetString("FeatureAirDropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlimited ammo. ähnelt.
        /// </summary>
        internal static string FeatureAmmunitionDescription {
            get {
                return ResourceManager.GetString("FeatureAmmunitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ammo ähnelt.
        /// </summary>
        internal static string FeatureAmmunitionName {
            get {
                return ResourceManager.GetString("FeatureAmmunitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Force all guns (even bolt action guns) to use automatic firing mode with customizable fire rate. ähnelt.
        /// </summary>
        internal static string FeatureAutomaticGunDescription {
            get {
                return ResourceManager.GetString("FeatureAutomaticGunDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die autogun ähnelt.
        /// </summary>
        internal static string FeatureAutomaticGunName {
            get {
                return ResourceManager.GetString("FeatureAutomaticGunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free camera with fast mode and teleportation. ähnelt.
        /// </summary>
        internal static string FeatureCameraDescription {
            get {
                return ResourceManager.GetString("FeatureCameraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die camera ähnelt.
        /// </summary>
        internal static string FeatureCameraName {
            get {
                return ResourceManager.GetString("FeatureCameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This main popup window. ähnelt.
        /// </summary>
        internal static string FeatureCommandsDescription {
            get {
                return ResourceManager.GetString("FeatureCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die commands ähnelt.
        /// </summary>
        internal static string FeatureCommandsName {
            get {
                return ResourceManager.GetString("FeatureCommandsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EFT Trainer ähnelt.
        /// </summary>
        internal static string FeatureCommandsTitle {
            get {
                return ResourceManager.GetString("FeatureCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crosshair with customizable size, color, thickness and auto-hide feature when aiming. ähnelt.
        /// </summary>
        internal static string FeatureCrosshairDescription {
            get {
                return ResourceManager.GetString("FeatureCrosshairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die crosshair ähnelt.
        /// </summary>
        internal static string FeatureCrosshairName {
            get {
                return ResourceManager.GetString("FeatureCrosshairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum durability of items. ähnelt.
        /// </summary>
        internal static string FeatureDurabilityDescription {
            get {
                return ResourceManager.GetString("FeatureDurabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die durability ähnelt.
        /// </summary>
        internal static string FeatureDurabilityName {
            get {
                return ResourceManager.GetString("FeatureDurabilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All items already examined. Instant search. ähnelt.
        /// </summary>
        internal static string FeatureExamineDescription {
            get {
                return ResourceManager.GetString("FeatureExamineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die examine ähnelt.
        /// </summary>
        internal static string FeatureExamineName {
            get {
                return ResourceManager.GetString("FeatureExamineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exfiltration points with customizable colors given eligibility, status filter, distance. ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsDescription {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ({1}) ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsEligibleFormat {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsEligibleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die exfil ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsName {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusActivate {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closed ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusClosed {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusOpen {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pending ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusPending {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requirement ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusRequirement {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer ähnelt.
        /// </summary>
        internal static string FeatureExfiltrationPointsStatusTimer {
            get {
                return ResourceManager.GetString("FeatureExfiltrationPointsStatusTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shoot through wall/helmet/vest/material with maximum penetration and minimal deviation/ricochet. ähnelt.
        /// </summary>
        internal static string FeatureFeatureWallShootDescription {
            get {
                return ResourceManager.GetString("FeatureFeatureWallShootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Field Of View (FOV). ähnelt.
        /// </summary>
        internal static string FeatureFovChangerDescription {
            get {
                return ResourceManager.GetString("FeatureFovChangerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fovchanger ähnelt.
        /// </summary>
        internal static string FeatureFovChangerName {
            get {
                return ResourceManager.GetString("FeatureFovChangerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh all game information for other features. ähnelt.
        /// </summary>
        internal static string FeatureGameStateDescription {
            get {
                return ResourceManager.GetString("FeatureGameStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gamestate ähnelt.
        /// </summary>
        internal static string FeatureGameStateName {
            get {
                return ResourceManager.GetString("FeatureGameStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop bots from seeing you. ähnelt.
        /// </summary>
        internal static string FeatureGhostDescription {
            get {
                return ResourceManager.GetString("FeatureGhostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ghost ähnelt.
        /// </summary>
        internal static string FeatureGhostName {
            get {
                return ResourceManager.GetString("FeatureGhostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grenades outline. ähnelt.
        /// </summary>
        internal static string FeatureGrenadesDescription {
            get {
                return ResourceManager.GetString("FeatureGrenadesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grenade ähnelt.
        /// </summary>
        internal static string FeatureGrenadesName {
            get {
                return ResourceManager.GetString("FeatureGrenadesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full health, prevent any damage (so even when falling), keep energy and hydration at maximum. ähnelt.
        /// </summary>
        internal static string FeatureHealthDescription {
            get {
                return ResourceManager.GetString("FeatureHealthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die health ähnelt.
        /// </summary>
        internal static string FeatureHealthName {
            get {
                return ResourceManager.GetString("FeatureHealthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hit markers (hit, armor, health with configurable colors). ähnelt.
        /// </summary>
        internal static string FeatureHitsDescription {
            get {
                return ResourceManager.GetString("FeatureHitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hits ähnelt.
        /// </summary>
        internal static string FeatureHitsName {
            get {
                return ResourceManager.GetString("FeatureHitsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ({0},{1}) ähnelt.
        /// </summary>
        internal static string FeatureHudCoordinatesFormat {
            get {
                return ResourceManager.GetString("FeatureHudCoordinatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HUD (compass, ammo left in chamber / magazine, fire mode, coordinates). ähnelt.
        /// </summary>
        internal static string FeatureHudDescription {
            get {
                return ResourceManager.GetString("FeatureHudDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hud ähnelt.
        /// </summary>
        internal static string FeatureHudName {
            get {
                return ResourceManager.GetString("FeatureHudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  -  ähnelt.
        /// </summary>
        internal static string FeatureHudSeparator {
            get {
                return ResourceManager.GetString("FeatureHudSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}+{1}/{2} [{3}] ähnelt.
        /// </summary>
        internal static string FeatureHudWeaponFormat {
            get {
                return ResourceManager.GetString("FeatureHudWeaponFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change distance for loot/door interaction. ähnelt.
        /// </summary>
        internal static string FeatureInteractDescription {
            get {
                return ResourceManager.GetString("FeatureInteractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die interact ähnelt.
        /// </summary>
        internal static string FeatureInteractName {
            get {
                return ResourceManager.GetString("FeatureInteractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List all lootable items and track any item by name or rarity or in-game wishlist in raid (even in containers and corpses). Use track and tracklist commands to control display. ähnelt.
        /// </summary>
        internal static string FeatureLootItemsDescription {
            get {
                return ResourceManager.GetString("FeatureLootItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loot ähnelt.
        /// </summary>
        internal static string FeatureLootItemsName {
            get {
                return ResourceManager.GetString("FeatureLootItemsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full screen map with radar esp. ähnelt.
        /// </summary>
        internal static string FeatureMapDescription {
            get {
                return ResourceManager.GetString("FeatureMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die map ähnelt.
        /// </summary>
        internal static string FeatureMapName {
            get {
                return ResourceManager.GetString("FeatureMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Triggers a mortar strike at the player&apos;s location. ähnelt.
        /// </summary>
        internal static string FeatureMortarDescription {
            get {
                return ResourceManager.GetString("FeatureMortarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mortar ähnelt.
        /// </summary>
        internal static string FeatureMortarName {
            get {
                return ResourceManager.GetString("FeatureMortarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Night vision. ähnelt.
        /// </summary>
        internal static string FeatureNightVisionDescription {
            get {
                return ResourceManager.GetString("FeatureNightVisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die night ähnelt.
        /// </summary>
        internal static string FeatureNightVisionName {
            get {
                return ResourceManager.GetString("FeatureNightVisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No physical collisions, making you immune to bullets, grenades and barbed wires. ähnelt.
        /// </summary>
        internal static string FeatureNoCollisionDescription {
            get {
                return ResourceManager.GetString("FeatureNoCollisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nocoll ähnelt.
        /// </summary>
        internal static string FeatureNoCollisionName {
            get {
                return ResourceManager.GetString("FeatureNoCollisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No persistent flash or eye-burn effect after a flash grenade. ähnelt.
        /// </summary>
        internal static string FeatureNoFlashDescription {
            get {
                return ResourceManager.GetString("FeatureNoFlashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die noflash ähnelt.
        /// </summary>
        internal static string FeatureNoFlashName {
            get {
                return ResourceManager.GetString("FeatureNoFlashName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No weapon malfunctions: no misfires or failures to eject or feed. No jammed bolts or overheating. ähnelt.
        /// </summary>
        internal static string FeatureNoMalfunctionsDescription {
            get {
                return ResourceManager.GetString("FeatureNoMalfunctionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nomal ähnelt.
        /// </summary>
        internal static string FeatureNoMalfunctionsName {
            get {
                return ResourceManager.GetString("FeatureNoMalfunctionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No recoil. ähnelt.
        /// </summary>
        internal static string FeatureNoRecoilDescription {
            get {
                return ResourceManager.GetString("FeatureNoRecoilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die norecoil ähnelt.
        /// </summary>
        internal static string FeatureNoRecoilName {
            get {
                return ResourceManager.GetString("FeatureNoRecoilName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sway. ähnelt.
        /// </summary>
        internal static string FeatureNoSwayDescription {
            get {
                return ResourceManager.GetString("FeatureNoSwayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nosway ähnelt.
        /// </summary>
        internal static string FeatureNoSwayName {
            get {
                return ResourceManager.GetString("FeatureNoSwayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No visor, so even when using a face shield-visor you won&apos;t see it. ähnelt.
        /// </summary>
        internal static string FeatureNoVisorDescription {
            get {
                return ResourceManager.GetString("FeatureNoVisorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die novisor ähnelt.
        /// </summary>
        internal static string FeatureNoVisorName {
            get {
                return ResourceManager.GetString("FeatureNoVisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Players (you&apos;ll see Bear/Boss/Cultist/Scav/Usec with configurable colors through walls). Charms, boxes, info (weapon and health), skeletons and distance. ähnelt.
        /// </summary>
        internal static string FeaturePlayersDescription {
            get {
                return ResourceManager.GetString("FeaturePlayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1}% {2} ähnelt.
        /// </summary>
        internal static string FeaturePlayersFormat {
            get {
                return ResourceManager.GetString("FeaturePlayersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die players ähnelt.
        /// </summary>
        internal static string FeaturePlayersName {
            get {
                return ResourceManager.GetString("FeaturePlayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [{0}m] ähnelt.
        /// </summary>
        internal static string FeaturePointOfInterestsDistanceFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsDistanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} {2} ähnelt.
        /// </summary>
        internal static string FeaturePointOfInterestsFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &gt;&gt; In {0} {1} ähnelt.
        /// </summary>
        internal static string FeaturePointOfInterestsGroupFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (in {0}) ähnelt.
        /// </summary>
        internal static string FeaturePointOfInterestsOwnerFormat {
            get {
                return ResourceManager.GetString("FeaturePointOfInterestsOwnerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locations for taking/placing quest items. Only items related to your started quests are displayed. ähnelt.
        /// </summary>
        internal static string FeatureQuestsDescription {
            get {
                return ResourceManager.GetString("FeatureQuestsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ({1}) ähnelt.
        /// </summary>
        internal static string FeatureQuestsFormat {
            get {
                return ResourceManager.GetString("FeatureQuestsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die quest ähnelt.
        /// </summary>
        internal static string FeatureQuestsName {
            get {
                return ResourceManager.GetString("FeatureQuestsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick-throw grenades. ähnelt.
        /// </summary>
        internal static string FeatureQuickTrowDescription {
            get {
                return ResourceManager.GetString("FeatureQuickTrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die quickthrow ähnelt.
        /// </summary>
        internal static string FeatureQuickTrowName {
            get {
                return ResourceManager.GetString("FeatureQuickTrowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2D radar. ähnelt.
        /// </summary>
        internal static string FeatureRadarDescription {
            get {
                return ResourceManager.GetString("FeatureRadarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die radar ähnelt.
        /// </summary>
        internal static string FeatureRadarName {
            get {
                return ResourceManager.GetString("FeatureRadarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [summary] ähnelt.
        /// </summary>
        internal static string FeatureRendererSummary {
            get {
                return ResourceManager.GetString("FeatureRendererSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to EFT-Trainer ! ähnelt.
        /// </summary>
        internal static string FeatureRendererWelcome {
            get {
                return ResourceManager.GetString("FeatureRendererWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All skills to Elite level (51) and all weapons mastering to level 3. ähnelt.
        /// </summary>
        internal static string FeatureSkillsDescription {
            get {
                return ResourceManager.GetString("FeatureSkillsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die skills ähnelt.
        /// </summary>
        internal static string FeatureSkillsName {
            get {
                return ResourceManager.GetString("FeatureSkillsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed boost to be able to go through walls/objects, or to move faster. Be careful to not kill yourself. ähnelt.
        /// </summary>
        internal static string FeatureSpeedDescription {
            get {
                return ResourceManager.GetString("FeatureSpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die speed ähnelt.
        /// </summary>
        internal static string FeatureSpeedName {
            get {
                return ResourceManager.GetString("FeatureSpeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlimited stamina. ähnelt.
        /// </summary>
        internal static string FeatureStaminaDescription {
            get {
                return ResourceManager.GetString("FeatureStaminaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stamina ähnelt.
        /// </summary>
        internal static string FeatureStaminaName {
            get {
                return ResourceManager.GetString("FeatureStaminaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hidden/special stashes like buried barrels, ground caches, air drops or corpses. ähnelt.
        /// </summary>
        internal static string FeatureStashDescription {
            get {
                return ResourceManager.GetString("FeatureStashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stash ähnelt.
        /// </summary>
        internal static string FeatureStashName {
            get {
                return ResourceManager.GetString("FeatureStashName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thermal vision. ähnelt.
        /// </summary>
        internal static string FeatureThermalVisionDescription {
            get {
                return ResourceManager.GetString("FeatureThermalVisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die thermal ähnelt.
        /// </summary>
        internal static string FeatureThermalVisionName {
            get {
                return ResourceManager.GetString("FeatureThermalVisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summon train on compatible maps like Reserve or Lighthouse. ähnelt.
        /// </summary>
        internal static string FeatureTrainDescription {
            get {
                return ResourceManager.GetString("FeatureTrainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die train ähnelt.
        /// </summary>
        internal static string FeatureTrainName {
            get {
                return ResourceManager.GetString("FeatureTrainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wallshoot ähnelt.
        /// </summary>
        internal static string FeatureWallShootName {
            get {
                return ResourceManager.GetString("FeatureWallShootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear weather. ähnelt.
        /// </summary>
        internal static string FeatureWeatherDescription {
            get {
                return ResourceManager.GetString("FeatureWeatherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weather ähnelt.
        /// </summary>
        internal static string FeatureWeatherName {
            get {
                return ResourceManager.GetString("FeatureWeatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Door/Keycard reader/Car unlocker. ähnelt.
        /// </summary>
        internal static string FeatureWorldInteractiveObjectsDescription {
            get {
                return ResourceManager.GetString("FeatureWorldInteractiveObjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die opener ähnelt.
        /// </summary>
        internal static string FeatureWorldInteractiveObjectsName {
            get {
                return ResourceManager.GetString("FeatureWorldInteractiveObjectsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor-damage color ähnelt.
        /// </summary>
        internal static string PropertyArmorDamageColor {
            get {
                return ResourceManager.GetString("PropertyArmorDamageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backward ähnelt.
        /// </summary>
        internal static string PropertyBackward {
            get {
                return ResourceManager.GetString("PropertyBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bear colors ähnelt.
        /// </summary>
        internal static string PropertyBearColors {
            get {
                return ResourceManager.GetString("PropertyBearColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Border color ähnelt.
        /// </summary>
        internal static string PropertyBorderColor {
            get {
                return ResourceManager.GetString("PropertyBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boss colors ähnelt.
        /// </summary>
        internal static string PropertyBossColors {
            get {
                return ResourceManager.GetString("PropertyBossColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Box thickness ähnelt.
        /// </summary>
        internal static string PropertyBoxThickness {
            get {
                return ResourceManager.GetString("PropertyBoxThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cache time (sec) ähnelt.
        /// </summary>
        internal static string PropertyCacheTimeInSec {
            get {
                return ResourceManager.GetString("PropertyCacheTimeInSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera offset ähnelt.
        /// </summary>
        internal static string PropertyCameraOffset {
            get {
                return ResourceManager.GetString("PropertyCameraOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change time ähnelt.
        /// </summary>
        internal static string PropertyChangeTime {
            get {
                return ResourceManager.GetString("PropertyChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        /// </summary>
        internal static string PropertyColor {
            get {
                return ResourceManager.GetString("PropertyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cultist colors ähnelt.
        /// </summary>
        internal static string PropertyCultistColors {
            get {
                return ResourceManager.GetString("PropertyCultistColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable XP Penalty ähnelt.
        /// </summary>
        internal static string PropertyDisableXpPenalty {
            get {
                return ResourceManager.GetString("PropertyDisableXpPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display time ähnelt.
        /// </summary>
        internal static string PropertyDisplayTime {
            get {
                return ResourceManager.GetString("PropertyDisplayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        internal static string PropertyDistance {
            get {
                return ResourceManager.GetString("PropertyDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elevation adjustment ähnelt.
        /// </summary>
        internal static string PropertyElevationAdjustment {
            get {
                return ResourceManager.GetString("PropertyElevationAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eligible color ähnelt.
        /// </summary>
        internal static string PropertyEligibleColor {
            get {
                return ResourceManager.GetString("PropertyEligibleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        internal static string PropertyEnabled {
            get {
                return ResourceManager.GetString("PropertyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable XP Multiplier ähnelt.
        /// </summary>
        internal static string PropertyEnableXpMultiplier {
            get {
                return ResourceManager.GetString("PropertyEnableXpMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fade-out time ähnelt.
        /// </summary>
        internal static string PropertyFadeOutTime {
            get {
                return ResourceManager.GetString("PropertyFadeOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fast mode ähnelt.
        /// </summary>
        internal static string PropertyFastMode {
            get {
                return ResourceManager.GetString("PropertyFastMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fast movement speed ähnelt.
        /// </summary>
        internal static string PropertyFastMovementSpeed {
            get {
                return ResourceManager.GetString("PropertyFastMovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Food / water ähnelt.
        /// </summary>
        internal static string PropertyFoodWater {
            get {
                return ResourceManager.GetString("PropertyFoodWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forward ähnelt.
        /// </summary>
        internal static string PropertyForward {
            get {
                return ResourceManager.GetString("PropertyForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FOV ähnelt.
        /// </summary>
        internal static string PropertyFov {
            get {
                return ResourceManager.GetString("PropertyFov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FOV circle color ähnelt.
        /// </summary>
        internal static string PropertyFovCircleColor {
            get {
                return ResourceManager.GetString("PropertyFovCircleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FOV circle thickness ähnelt.
        /// </summary>
        internal static string PropertyFovCircleThickness {
            get {
                return ResourceManager.GetString("PropertyFovCircleThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FOV radius ähnelt.
        /// </summary>
        internal static string PropertyFovRadius {
            get {
                return ResourceManager.GetString("PropertyFovRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free look sensitivity ähnelt.
        /// </summary>
        internal static string PropertyFreeLookSensitivity {
            get {
                return ResourceManager.GetString("PropertyFreeLookSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grouping Color ähnelt.
        /// </summary>
        internal static string PropertyGroupingColor {
            get {
                return ResourceManager.GetString("PropertyGroupingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Health-damage color ähnelt.
        /// </summary>
        internal static string PropertyHealthDamageColor {
            get {
                return ResourceManager.GetString("PropertyHealthDamageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide when aiming ähnelt.
        /// </summary>
        internal static string PropertyHideWhenAiming {
            get {
                return ResourceManager.GetString("PropertyHideWhenAiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hit-marker color ähnelt.
        /// </summary>
        internal static string PropertyHitMarkerColor {
            get {
                return ResourceManager.GetString("PropertyHitMarkerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info color ähnelt.
        /// </summary>
        internal static string PropertyInfoColor {
            get {
                return ResourceManager.GetString("PropertyInfoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intensity ähnelt.
        /// </summary>
        internal static string PropertyIntensity {
            get {
                return ResourceManager.GetString("PropertyIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        internal static string PropertyKey {
            get {
                return ResourceManager.GetString("PropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        internal static string PropertyLeft {
            get {
                return ResourceManager.GetString("PropertyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marksman colors ähnelt.
        /// </summary>
        internal static string PropertyMarksmanColors {
            get {
                return ResourceManager.GetString("PropertyMarksmanColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum distance ähnelt.
        /// </summary>
        internal static string PropertyMaximumDistance {
            get {
                return ResourceManager.GetString("PropertyMaximumDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Movement speed ähnelt.
        /// </summary>
        internal static string PropertyMovementSpeed {
            get {
                return ResourceManager.GetString("PropertyMovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not eligible color ähnelt.
        /// </summary>
        internal static string PropertyNotEligibleColor {
            get {
                return ResourceManager.GetString("PropertyNotEligibleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not shootable colors ähnelt.
        /// </summary>
        internal static string PropertyNotShootableColors {
            get {
                return ResourceManager.GetString("PropertyNotShootableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radar background ähnelt.
        /// </summary>
        internal static string PropertyRadarBackground {
            get {
                return ResourceManager.GetString("PropertyRadarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radar crosshair ähnelt.
        /// </summary>
        internal static string PropertyRadarCrosshair {
            get {
                return ResourceManager.GetString("PropertyRadarCrosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radar percentage ähnelt.
        /// </summary>
        internal static string PropertyRadarPercentage {
            get {
                return ResourceManager.GetString("PropertyRadarPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radar range ähnelt.
        /// </summary>
        internal static string PropertyRadarRange {
            get {
                return ResourceManager.GetString("PropertyRadarRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range ähnelt.
        /// </summary>
        internal static string PropertyRange {
            get {
                return ResourceManager.GetString("PropertyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate ähnelt.
        /// </summary>
        internal static string PropertyRate {
            get {
                return ResourceManager.GetString("PropertyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove negative effects ähnelt.
        /// </summary>
        internal static string PropertyRemoveNegativeEffects {
            get {
                return ResourceManager.GetString("PropertyRemoveNegativeEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        internal static string PropertyRight {
            get {
                return ResourceManager.GetString("PropertyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rogue-Usec colors ähnelt.
        /// </summary>
        internal static string PropertyRogueUsecColors {
            get {
                return ResourceManager.GetString("PropertyRogueUsecColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scav-assault colors ähnelt.
        /// </summary>
        internal static string PropertyScavAssaultColors {
            get {
                return ResourceManager.GetString("PropertyScavAssaultColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scav colors ähnelt.
        /// </summary>
        internal static string PropertyScavColors {
            get {
                return ResourceManager.GetString("PropertyScavColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scav-raider colors ähnelt.
        /// </summary>
        internal static string PropertyScavRaiderColors {
            get {
                return ResourceManager.GetString("PropertyScavRaiderColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search inside containers ähnelt.
        /// </summary>
        internal static string PropertySearchInsideContainers {
            get {
                return ResourceManager.GetString("PropertySearchInsideContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search inside corpses ähnelt.
        /// </summary>
        internal static string PropertySearchInsideCorpses {
            get {
                return ResourceManager.GetString("PropertySearchInsideCorpses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shootable colors ähnelt.
        /// </summary>
        internal static string PropertyShootableColors {
            get {
                return ResourceManager.GetString("PropertyShootableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show armor damage ähnelt.
        /// </summary>
        internal static string PropertyShowArmorDamage {
            get {
                return ResourceManager.GetString("PropertyShowArmorDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Bosses ähnelt.
        /// </summary>
        internal static string PropertyShowBosses {
            get {
                return ResourceManager.GetString("PropertyShowBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show boxes ähnelt.
        /// </summary>
        internal static string PropertyShowBoxes {
            get {
                return ResourceManager.GetString("PropertyShowBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show charms ähnelt.
        /// </summary>
        internal static string PropertyShowCharms {
            get {
                return ResourceManager.GetString("PropertyShowCharms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show compass ähnelt.
        /// </summary>
        internal static string PropertyShowCompass {
            get {
                return ResourceManager.GetString("PropertyShowCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show containers ähnelt.
        /// </summary>
        internal static string PropertyShowContainers {
            get {
                return ResourceManager.GetString("PropertyShowContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show coordinates ähnelt.
        /// </summary>
        internal static string PropertyShowCoordinates {
            get {
                return ResourceManager.GetString("PropertyShowCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show corpses ähnelt.
        /// </summary>
        internal static string PropertyShowCorpses {
            get {
                return ResourceManager.GetString("PropertyShowCorpses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Cultists ähnelt.
        /// </summary>
        internal static string PropertyShowCultists {
            get {
                return ResourceManager.GetString("PropertyShowCultists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show eligible ähnelt.
        /// </summary>
        internal static string PropertyShowEligible {
            get {
                return ResourceManager.GetString("PropertyShowEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show fov circle ähnelt.
        /// </summary>
        internal static string PropertyShowFovCircle {
            get {
                return ResourceManager.GetString("PropertyShowFovCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show health-damage ähnelt.
        /// </summary>
        internal static string PropertyShowHealthDamage {
            get {
                return ResourceManager.GetString("PropertyShowHealthDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Hit-marker ähnelt.
        /// </summary>
        internal static string PropertyShowHitMarker {
            get {
                return ResourceManager.GetString("PropertyShowHitMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show infos ähnelt.
        /// </summary>
        internal static string PropertyShowInfos {
            get {
                return ResourceManager.GetString("PropertyShowInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show map ähnelt.
        /// </summary>
        internal static string PropertyShowMap {
            get {
                return ResourceManager.GetString("PropertyShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Marksmen ähnelt.
        /// </summary>
        internal static string PropertyShowMarksmen {
            get {
                return ResourceManager.GetString("PropertyShowMarksmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show not eligible ähnelt.
        /// </summary>
        internal static string PropertyShowNotEligible {
            get {
                return ResourceManager.GetString("PropertyShowNotEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show not shootable ähnelt.
        /// </summary>
        internal static string PropertyShowNotShootable {
            get {
                return ResourceManager.GetString("PropertyShowNotShootable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show players ähnelt.
        /// </summary>
        internal static string PropertyShowPlayers {
            get {
                return ResourceManager.GetString("PropertyShowPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show prices ähnelt.
        /// </summary>
        internal static string PropertyShowPrices {
            get {
                return ResourceManager.GetString("PropertyShowPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Rogues ähnelt.
        /// </summary>
        internal static string PropertyShowRogues {
            get {
                return ResourceManager.GetString("PropertyShowRogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Scav-assaults ähnelt.
        /// </summary>
        internal static string PropertyShowScavAssaults {
            get {
                return ResourceManager.GetString("PropertyShowScavAssaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Scav-raiders ähnelt.
        /// </summary>
        internal static string PropertyShowScavRaiders {
            get {
                return ResourceManager.GetString("PropertyShowScavRaiders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Scavs ähnelt.
        /// </summary>
        internal static string PropertyShowScavs {
            get {
                return ResourceManager.GetString("PropertyShowScavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show shootable ähnelt.
        /// </summary>
        internal static string PropertyShowShootable {
            get {
                return ResourceManager.GetString("PropertyShowShootable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show skeletons ähnelt.
        /// </summary>
        internal static string PropertyShowSkeletons {
            get {
                return ResourceManager.GetString("PropertyShowSkeletons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silent aim ähnelt.
        /// </summary>
        internal static string PropertySilentAim {
            get {
                return ResourceManager.GetString("PropertySilentAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silent aim next-shot-delay ähnelt.
        /// </summary>
        internal static string PropertySilentAimNextShotDelay {
            get {
                return ResourceManager.GetString("PropertySilentAimNextShotDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silent aim speed-factor ähnelt.
        /// </summary>
        internal static string PropertySilentAimSpeedFactor {
            get {
                return ResourceManager.GetString("PropertySilentAimSpeedFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        internal static string PropertySize {
            get {
                return ResourceManager.GetString("PropertySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skeleton thickness ähnelt.
        /// </summary>
        internal static string PropertySkeletonThickness {
            get {
                return ResourceManager.GetString("PropertySkeletonThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smoothness ähnelt.
        /// </summary>
        internal static string PropertySmoothness {
            get {
                return ResourceManager.GetString("PropertySmoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status filter ähnelt.
        /// </summary>
        internal static string PropertyStatusFilter {
            get {
                return ResourceManager.GetString("PropertyStatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teleport ähnelt.
        /// </summary>
        internal static string PropertyTeleport {
            get {
                return ResourceManager.GetString("PropertyTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thickness ähnelt.
        /// </summary>
        internal static string PropertyThickness {
            get {
                return ResourceManager.GetString("PropertyThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track Auto Wishlist ähnelt.
        /// </summary>
        internal static string PropertyTrackAutoWishlist {
            get {
                return ResourceManager.GetString("PropertyTrackAutoWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Example: [&quot;foo&quot;, &quot;bar&quot;] or with extended properties: [{&quot;Name&quot;:&quot;foo&quot;,&quot;Color&quot;:[1.0,0.0,0.0,1.0]},{&quot;Name&quot;:&quot;bar&quot;,&quot;Color&quot;:[1.0,1.0,1.0,0.8],&quot;Rarity&quot;:&quot;Rare&quot;}] ähnelt.
        /// </summary>
        internal static string PropertyTrackedNamesComment {
            get {
                return ResourceManager.GetString("PropertyTrackedNamesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track Wishlist ähnelt.
        /// </summary>
        internal static string PropertyTrackWishlist {
            get {
                return ResourceManager.GetString("PropertyTrackWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usec colors ähnelt.
        /// </summary>
        internal static string PropertyUsecColors {
            get {
                return ResourceManager.GetString("PropertyUsecColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vitals only ähnelt.
        /// </summary>
        internal static string PropertyVitalsOnly {
            get {
                return ResourceManager.GetString("PropertyVitalsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X ähnelt.
        /// </summary>
        internal static string PropertyX {
            get {
                return ResourceManager.GetString("PropertyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XP Multiplier ähnelt.
        /// </summary>
        internal static string PropertyXpMultiplier {
            get {
                return ResourceManager.GetString("PropertyXpMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XRay-Vision ähnelt.
        /// </summary>
        internal static string PropertyXRayVision {
            get {
                return ResourceManager.GetString("PropertyXRayVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y ähnelt.
        /// </summary>
        internal static string PropertyY {
            get {
                return ResourceManager.GetString("PropertyY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die off ähnelt.
        /// </summary>
        internal static string TextOff {
            get {
                return ResourceManager.GetString("TextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on ähnelt.
        /// </summary>
        internal static string TextOn {
            get {
                return ResourceManager.GetString("TextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ------ ähnelt.
        /// </summary>
        internal static string TextSeparator {
            get {
                return ResourceManager.GetString("TextSeparator", resourceCulture);
            }
        }
    }
}
